### ISSUE TITLE
[Bug] External compiler not working?

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#128]
I've set the compiler in preferences window (no error message occured as it founds cobc). When I compile "anything" the compilation button gets disabled, no error message occurs, no entry in Logs window is added.

cobc -V and cobc --info can be run from the environment where I've started OCIDE from (PATh environment is set correct).

If there is a problem during compiler call the problem should be shown to the user.

## System information

- OpenCobolIDE: 4.6.0.dev0
- GnuCobol: 001-2
- Python: 3.4.3 (64bits)
- Qt: 4.8.6
- PyQt: 4.11.3
- pyqode.core: 2.6.2
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Does it work if you restart the IDE? OCIDE setups some environmnent variables needed to make the bundled OpenCOBOL work out of the box, these environmnet variables are setup during startup and may conflict with the external compiler you set up until you restart the IDE...

If that does not work, it might help to paste the application log after a failure (Help->About->Log)

Is that a mingw build of OpenCOBOL or a MSVC  build? When I tested the external compiler feature, I tested it with a build from http://www.kiska.net/opencobol/. It might help if I could download a build of the version you tried.

**Comment by ColinDuquesnoy** [comment]
Hmm I think it might be useful to let the user override the following environment variables as well when a external compiler has been setup:

- PATH
- COB_CONFIG_DIR
- COB_COPY_DIR
- COB_LIBRARY_PATH
- COB_INCLUDE_PATH
- COB_LIB_PATH

I will add those the compiler preferences

**Comment by ColinDuquesnoy** [comment]
Now that #127 and #129 have been implemented, you should have better tools to detect what's wrong. I suggest you to pull the latest revision on master branch and try again.

Since you're running from git checkout, you can run the IDE from a terminal and paste the traceback here in case something went wrong (the traceback might a valuable piece of information when debugging this issue).

**Comment by GitMensch** [comment]
I've tried to run this with a Cygwin build (from source tree --> no 'make install' done).
The Log from About menu does only show:

DEBUG::open_cobol_ide.compilers::getting cobc version: cobc --version
DEBUG::open_cobol_ide.compilers::parsing version line: b''
INFO::open_cobol_ide.compilers::OpenCOBOL compiler v.None

This is exactly what the command line outputs, too.
As the compiler does work when called directly (environment vars where set by either sourcing both ./tests/atlocal & ./test/atconfig or directly with an own set_env.bat) it could be usefull to disable the environment setttings. What do you think about adding a check box to the left oft each environment setting for enabling/disabling it?

**Comment by ColinDuquesnoy** [comment]
Yes I think this is a good idea. The IDE setup those env vars automatically to help out the newcomers but experts should definitely be able to disable those environment variables and configure their system as they want. 

Will let you know when this is available.

**Comment by GitMensch** [comment]
Upgrading PyQT to version 5 results in an error message during startup: missing dll.

At first I enjoyed it, but not when I recognized that this pops up during every edit because of called cobc...
Can I suggest to disable the calls to cobc if cobc --version did not worked until next time it is checked (which would be either a restart or a change in compiler settings)?

Hm, the button "Check compiler" in preferences still only shows "Compiler check failed" with no reason.

BTW: the "missing" dll is part of PATH in preferences dialog...

**Comment by ColinDuquesnoy** [comment]
I am not sure I understand what happen here. A screenshot and the standard output might help (any python traceback when running from a terminal)?

**Comment by GitMensch** [comment]
What part didn't you understand? I'll provide screens and whatever needed :-)
Should I open a new ticket for not calling cobc until cobc --version works?

**Comment by ColinDuquesnoy** [comment]
Well the part with calling cobc: the IDE call cobc --version on startup and only when you hit the compile button. It also call cobc in a background process but that should not cause a popup to show up. I'd like to see the actual popup.

**Comment by GitMensch** [comment]
The background call is exactly what I'm referring to. If cobc --version doesn't work it has no good of calling cobc in background, does it?

The error message in this specific case (missing dll for cobc) is the standard system error message from windows:

---------------------------
cobc.exe - system error
---------------------------
This application has failed to start because cygwin1.dll was not found.  Re-installing the application may fix this problem.
---------------------------
OK   
---------------------------

**Comment by ColinDuquesnoy** [comment]
Oh ok now I understand, yes disabling linter while compiler is not working makes sense.

**Comment by ColinDuquesnoy** [comment]
Should be fixed with the latest commit.

**Comment by ColinDuquesnoy** [comment]
I also improved the check compiler button to include the exit code and the process output. Now it also handled crashed process (segfault,...).

**Comment by GitMensch** [comment]
Sorry it doesn't work - the error message even pops up more... (if I insert a space somewhere the message is shown two times).

If you use a new GC2.0 version it's easy to get the same behavior: simply rename libcob.dll as it's called from cobc, too. Otherwise use depends.exe to view the dependencies of your cobc and rename one of the shown dlls.

This is what the improved "check compiler" outputs (nice improvement work here):

---------------------------
Check compiler
---------------------------
Complier check failed:

Exit code: -1073741515
Output:
---------------------------
OK   
---------------------------

**Comment by ColinDuquesnoy** [comment]
> Sorry it doesn't work - the error message even pops up more... (if I insert a space somewhere the message is shown two times).

Oops, looks like I made the change on the wrong files (in build directory instead of the sources...) Should be working now...

```
Complier check failed:

Exit code: -1073741515
```

Mmm... so no output (neither from stdout nor from stderr) and a non-zero return code, looks like the cobc process has crashed. Did you try with all environment vars disabled? Tomorrow I'll try to make a small python script for you to experiment with (so that you can inspect environment variables,... and see what's wrong).

**Comment by GitMensch** [comment]
Still doesn't work, the error pops up over and over :-(

**Comment by ColinDuquesnoy** [comment]
I added more debug messages for when the linter get disabled enabled. Please try again and paste the output log.

I also added more messages to the check compiler function, it will print its environment.

PS: I am running the bundled OpenCobol compiler. According to depends.exe it depends only on msvcrt so I not yet able to reproduce your situation. Going to try with GnuCobol 2.0 (MSVC build) tomorrow.

**Comment by GitMensch** [comment]
It's better now - no background calls any more.

The messages occurred on startup (first) + opening a file (second and third).

This is the log from the start:

```
D:\dev\Python\Scripts>D:\dev\Python\python.exe D:\dev\Python\Scripts\OpenCobolIDE-script.pyw
Qt: Untested Windows version 10.0 detected!
INFO::open_cobol_ide::version: 4.6.0.dev0
DEBUG::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-log': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>, 'text/plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>}
DEBUG::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>}
DEBUG::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>}
DEBUG::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-plain': <class 'open_cobol_ide.view.editors.text.TextEdit'>, 'text/x-log': <class 'open_cobol_ide.view.editors.text.TextEdit'>, 'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>, 'text/plain': <class 'open_cobol_ide.view.editors.text.TextEdit'>}
DEBUG::open_cobol_ide.controllers.view::showing page <Page.HOME: 0>
DEBUG::open_cobol_ide.compilers::getting cobc version: cobc --version
DEBUG::open_cobol_ide.compilers::parsing version line: b''
INFO::open_cobol_ide.compilers::OpenCOBOL compiler v.None
DEBUG::pyqode.core.api.client::backend process started
DEBUG::pyqode.core.managers.backend::starting backend process: D:\dev\Python\python.exe D:\dev\Python\lib\site-packages\pyqode\cobol\backend\server.py 63481
DEBUG::pyqode.core.api.panel::ControlPanel visibility changed
DEBUG::pyqode.core.managers.panels::adding panel ControlPanel at 'right'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel ControlPanel installed
DEBUG::pyqode.core.managers.panels::adding panel SearchAndReplacePanel at 'bottom'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.api.panel::SearchAndReplacePanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel SearchAndReplacePanel installed
DEBUG::pyqode.core.managers.panels::adding panel FoldingPanel at 'left'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel FoldingPanel installed
DEBUG::pyqode.core.managers.panels::adding panel LineNumberPanel at 'left'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel LineNumberPanel installed
DEBUG::pyqode.core.managers.panels::adding panel CheckerPanel at 'left'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel CheckerPanel installed
DEBUG::pyqode.core.managers.panels::adding panel GlobalCheckerPanel at 'right'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel GlobalCheckerPanel installed
DEBUG::pyqode.core.managers.modes::adding mode 'ExtendedSelectionMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CaseConverterMode'
DEBUG::pyqode.core.managers.modes::adding mode 'AutoCompleteMode'
DEBUG::pyqode.core.managers.modes::adding mode 'OutlineMode'
DEBUG::pyqode.core.managers.modes::adding mode 'GoToDefinitionMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CodeCompletionMode'
DEBUG::pyqode.core.managers.modes::adding mode 'FileWatcherMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CobolAutoIndentMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CaretLineHighlighterMode'
DEBUG::pyqode.core.managers.modes::adding mode 'ZoomMode'
DEBUG::pyqode.core.managers.modes::adding mode 'IndenterMode'
DEBUG::pyqode.core.managers.modes::adding mode 'AutoIndentMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CobolSyntaxHighlighter'
DEBUG::pyqode.core.managers.modes::adding mode 'LeftMarginMode'
DEBUG::pyqode.core.managers.modes::adding mode 'RightMarginMode'
DEBUG::pyqode.core.managers.modes::adding mode 'CommentsMode'
DEBUG::pyqode.core.managers.modes::adding mode 'OffsetCalculatorMode'
DEBUG::pyqode.core.managers.modes::adding mode 'OccurrencesHighlighterMode'
DEBUG::pyqode.core.managers.modes::adding mode 'SmartBackSpaceMode'
DEBUG::pyqode.core.api.panel::EncodingPanel visibility changed
DEBUG::pyqode.core.managers.panels::adding panel EncodingPanel at 'top'
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.managers.panels::panel EncodingPanel installed
DEBUG::pyqode.core.managers.modes::adding mode 'CobolLinterMode'
DEBUG::pyqode.core.modes.checker [CobolLinterMode]::running analysis
DEBUG::open_cobol_ide.compilers::getting cobc version: cobc --version
DEBUG::open_cobol_ide.compilers::parsing version line: b''
INFO::open_cobol_ide.compilers::OpenCOBOL compiler v.None
INFO::open_cobol_ide.view.editors.cobol::linter enabled: False
DEBUG::pyqode.core.managers.file::detecting mimetype for bench.cbl
DEBUG::pyqode.core.managers.file::mimetype detected: text/x-cobol
DEBUG::pyqode.core.api.code_edit::setPlainText duration: 0.043002s
DEBUG::pyqode.core.managers.backend::sending request, worker=<function get_outline at 0x0000000005585AE8>
DEBUG::pyqode.core.api.client::connecting to 127.0.0.1:63481
DEBUG::pyqode.core.api.panel::ControlPanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.widgets.splittable_tab_widget::current tab changed (old=None, new=CobolCodeEdit(path='D:\\dev\\GnuCOBOL\\own_tests\\bench.cbl'))
DEBUG::pyqode.core.widgets.filesystem_treeview::accepting D:/
DEBUG::pyqode.core.widgets.filesystem_treeview::accepting D:/dev
DEBUG::pyqode.core.widgets.filesystem_treeview::accepting D:/dev/GnuCOBOL
DEBUG::open_cobol_ide.compilers::detecting file type: D:\dev\GnuCOBOL\own_tests\bench.cbl - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.EXECUTABLE: 0>
DEBUG::open_cobol_ide.compilers::detecting file type: D:\dev\GnuCOBOL\own_tests\bench.cbl - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.EXECUTABLE: 0>
INFO::open_cobol_ide.controllers.edit::current editor changed: D:\dev\GnuCOBOL\own_tests\bench.cbl
DEBUG::pyqode.core.api.panel::LineNumberPanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.modes.checker [CobolLinterMode]::running analysis
DEBUG::pyqode.core.managers.backend::sending request, worker=<function set_lower_case_keywords at 0x0000000005585A60>
DEBUG::pyqode.core.api.client::connecting to 127.0.0.1:63481
DEBUG::open_cobol_ide.compilers::getting cobc version: cobc --version
DEBUG::open_cobol_ide.compilers::parsing version line: b''
INFO::open_cobol_ide.compilers::OpenCOBOL compiler v.None
INFO::open_cobol_ide.view.editors.cobol::linter enabled: False
DEBUG::open_cobol_ide.compilers::detecting file type: D:\dev\GnuCOBOL\own_tests\bench.cbl - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.EXECUTABLE: 0>
DEBUG::open_cobol_ide.controllers.view::showing page <Page.EDIT: 1>
DEBUG::pyqode.core.api.panel::FoldingPanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.api.panel::CheckerPanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.api.panel::GlobalCheckerPanel visibility changed
DEBUG::pyqode.core.managers.panels::refresh_panels
DEBUG::pyqode.core.api.code_edit::show event: CobolCodeEdit(path='D:\\dev\\GnuCOBOL\\own_tests\\bench.cbl')
```
When I use the compile buttons OCIDE doesn't seem to hang any more (as it was on beginning the tests) but shows 

---------------------------
Cannot compile file
---------------------------
Cannot compile file: 'bench.cbl'.

Reason: GnuCOBOL compiler not found or not working
---------------------------
OK   
---------------------------

So this part is *fixed* for me, now going on to getting the compiler to work :-)

**Comment by GitMensch** [comment]
The compiler worked as soon as I removed the Checkbox for PATH. Looks like a bug as the PATH should only be prefixed (which would work even if the given path would be wrong).

**Comment by ColinDuquesnoy** [comment]
I've changed the way PATH is set. Could you try again with PATH check box checked?

**Comment by GitMensch** [comment]
Success.
When running from an environment where it works it now does even with enabling the PATH change.

But the PATH should not be appended but prefixed as users want these paths used, not the stuff that is in PATH before.

It's still open for me why it doesn't work from an environment where PATH is not set correctly (but the enabled PATH in OCIDE is "D:\dev\GnuCOBOL\gnu-cobol-svn\cobc;D:\dev\GnuCOBOL\gnu-cobol-svn\libcob\.libs" - the second one has the "missing" dll in it).

**Comment by ColinDuquesnoy** [comment]
> But the PATH should not be appended but prefixed as users want these paths used, not the stuff that is in PATH before.

Oh that's what you meant by prefixed. Should be alright now.

**Comment by GitMensch** [comment]
Isn't a delimiter missing?

Something along

´´´patch
-os.environ['PATH'].insert(0, s.path)
+string prefixpath = s.path
+if (win):
+   prefixpath += ";"
+else:
+   prefixpath += ":"
+os.environ['PATH'].insert(0, prefixpath)
´´´

**Comment by ColinDuquesnoy** [comment]
Yeah I noticed this just after committing (I begin to feel tired). I already fixed it in commit e8644527b43b4bff4ac8cab1a203f29906d10814

**Comment by ColinDuquesnoy** [comment]
> It's still open for me why it doesn't work from an environment where PATH is not set correctly (but the enabled PATH in OCIDE is "D:\dev\GnuCOBOL\gnu-cobol-svn\cobc;D:\dev\GnuCOBOL\gnu-cobol-svn\libcob.libs" - the second one has the "missing" dll in it).

Does it work now that the path is prefixed and not overriden?

**Comment by GitMensch** [comment]
Works only if "outside" PATH is fine. I still do not now why it doesn't work with PATH in OCIDE being "D:\dev\GnuCOBOL\gnu-cobol-svn\cobc;D:\dev\GnuCOBOL\gnu-cobol-svn\libcob.libs" (the second one has the "missing" dll in it).

**Comment by ColinDuquesnoy** [comment]
> Works only if "outside" PATH is fine.

I thought that the fact PATH is now prefixed would have solved that one :(

**Comment by GitMensch** [comment]
:-) Works fine with current revision, I just messed up the PATH setting in OCIDE during last (and late night) tests

You may want to solve the "cobc --version is called three times during startup" issue (I think it's best to call it on startup and passing the information received to other threads) before closing the bug.

**Comment by ColinDuquesnoy** [comment]
> :-) Works fine with current revision

Hooray!

> You may want to solve the "cobc --version is called three times during startup" issue

Mmm I missed that, thank you!

**Comment by ColinDuquesnoy** [comment]
Fixed (the result of check compiler is now memoized, cache is reset when you apply compiler preferences or when you run a manual check).

**Comment by GitMensch** [comment]
Good work, seems like I've to add new items now, to keep the nice flow ;-)

**Comment by GitMensch** [comment]
Looks like it doesn't work a expected - while the compiler within OCIDE does work perfectly the system information (and the bug report) show:

- OpenCobolIDE: 4.6.0.dev11
- GnuCOBOL: Not installed

The log says:

INFO::open_cobol_ide.compilers::GnuCOBOL compiler check: success
ERROR::open_cobol_ide.compilers::OpenCOBOL compiler not found

I do indeed have not OpenCOBOL available (it's GnuCOBOL).

Further checks from preferences:

---------------------------
Check compiler
---------------------------
Compiler works!
---------------------------
OK   
---------------------------

Using the compiler path to get more information lead to

---------------------------
Invalid compiler path
---------------------------
Not a valid compiler path because it does not contain cobc.exe!
---------------------------
OK   
---------------------------

Setting the path correct the output is

cobc (GNU Cobol) 2.0.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
Copyright (C) 2009,2010,2012,2014,2015 Simon Sobisch
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     May 27 2015 21:02:08
Packaged  Mrz 29 2015 14:56:23 UTC
C version "4.9.2"

The output in Log (and in the bug report) is now

INFO::open_cobol_ide.compilers::GnuCOBOL compiler check: success
INFO::open_cobol_ide.app::GnuCOBOL version: 2.0.0

What do you think, i there anything that should be changed in OCIDE?

**Comment by ColinDuquesnoy** [comment]
> I do indeed have not OpenCOBOL available (it's GnuCOBOL).

I don't make the difference between OpenCOBOL and GnuCOBOL, I'll fix those inconsistencies by using GnuCOBOL everywhere.

> GnuCOBOL: Not installed

Good catch! I am not on windows right now but I will defenitely have a look and fix that before the release.

**Comment by ColinDuquesnoy** [comment]
> In any case I suggest to open the "Check compiler" dialog when clicking on "check compiler" in preferences and rename the button "Check compiler" in this dialog to "Check compilation"

That's done

**Comment by ColinDuquesnoy** [comment]
> Setting the path correct the output is

What was the path value before you corrected it? Was the checkbox enabled?

**Comment by ColinDuquesnoy** [comment]
I think I fixed it (see latest commit). Please try again!

**Comment by GitMensch** [comment]
> >    In any case I suggest to open the "Check compiler" dialog when clicking on "check compiler" in preferences and rename the button "Check compiler" in this dialog to "Check compilation"

> That's been done

Hm, I wonder why we have [OK] (disabled by default) [Cancel] and [Check compilation] in this dialog. Is there any situation where [Cancel] would be useful? If not: please remove it (set to visible.false in the not needed situations otherwise) and enable [OK] by default.

> I think I fixed it (see latest commit). Please try again!
Yes, works fine.

**Comment by ColinDuquesnoy** [comment]
> Hm, I wonder why we have OK [Cancel] and [Check compilation] in this dialog. Is there any situation where [Cancel] would be useful? If not: please remove it (set to visible.false in the not needed situations otherwise) and enable [OK] by default.

You're right it is not used anymore (before, compiler path would only be set if you hit OK in the check compiler dialog but I changed that behavour to let user set and fix a non working compiler path).

**Comment by ColinDuquesnoy** [comment]
I removed the cancel button, rename Ok to Close (and keep it enabled)

**Comment by GitMensch** [comment]
Is there anything that should prevent the "advanced user" to change the compiler completely?
I've started to put production code into OCIDE just to recognize the current implementation does not work as we normally preparse the file (in this case grep/findstr for "@OC-FLAGS") and add the result to cobc command line (for supporting special switches per file which are stored within the source in svn).

My hack works but this shouldn't be necessary:

* create a batch file
* compile it to cobc.exe (there are different ways for doing so)
* point OCIDE to this file

I see no problem if anyone uses a MF, Fujitsu or whatever compiler as long as it works, so it would be nice to be able to change the COBOL compiler completely (this is NOT windows specific).

**Comment by ColinDuquesnoy** [comment]
I can see the following problems:

- compiler output parsing is usually very specific to one compiler
- compiler flags and enviironment variables are also very specific to one compiler
- for an unknown compiler, users will have to specify all compilation flags by themselves, i.e. iintegration won't be as good as for officially supported compilers
- my lack of knowledge and interest for other non-free compilers

All those issues are easy to solve: just let experimented users make the integration work themselves, by writing a compiler integration plugin.

**Comment by GitMensch** [comment]
OK, for new IDE this will be possible. For OCIDE please change the preferences to the full command (ie C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe) and use this everywhere.
This way one can "tweak" everything without being hacky...

**Comment by ColinDuquesnoy** [comment]
> C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe) and use this everywhere.

Reopening so that I don't forget it.

**Comment by ColinDuquesnoy** [comment]
> C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe) and use this everywhere.

Should be fixed, tested on linux only

**Comment by GitMensch** [comment]
Not checked the exact call, but is it possible to choose the actual binary/script (not only the folder)? In Unix this won't be a big problem as it's possible to have script without an extension and executables don't have one. But for windows this isn't true.

Why not letting the advanced user choose the full path to the compiler?

**Comment by ColinDuquesnoy** [comment]
I don't remember why I chose to do it that way (I wrote the compiler code
two years ago) but indeed atm you can only choose a directory. I think
there is no need to do it that way anymore so I might change that for v4.7
(maybe open a new issue that request for the full compiler path).

2015-06-05 18:05 GMT+02:00 GitMensch <notifications@github.com>:

> Not checked the exact call, but is it possible to choose the actual
> binary/script (not only the folder)? In Unix this won't be a big problem as
> it's possible to have script without an extension and executables don't
> have one. But for windows this isn't true.
>
> Why not letting the advanced user choose the full path to the compiler?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/128#issuecomment-109342524>
> .
>



-- 
Rue de l'Harmonie, 26
4800 Verviers
0475/335634
colin.duquesnoy@gmail.com
