### ISSUE TITLE
[Bug] Navigation widget: DIVISIONs/SECTIONs/PARAGRAPHS not recognized correctly

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#133]
Currently something like

       LINKAGE SECTION .

does not work as the check seems to be done for "SECTION." but the period can be everywhere (even on the next lines).

For PROCEDURE DIVISION keep in mind that nearly all programs have the USING clause:

      PROCEDURE DIVISION USING VAR, VAR2.

## System information

- OpenCobolIDE: 4.6.0.dev0
- GnuCOBOL: None
- Python: 3.4.3 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.2
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Yes the parser is still a bit sloppy, there are lots of room for improvements. If you find other cases, no need to open a new issue, just post them here ;)

**Comment by ColinDuquesnoy** [comment]
Should be working better now. Please note that statements that span over multiple lines are not handled correctly yet. This will get fixed in pyQode/pyQode#41.

**Comment by GitMensch** [comment]
The "only dead will cross this line" for external parsers is the following "perfectly fine but nowadays more than exotic and nearly never used continuation issue":

´´´COBOL
                                                      PROCEDURE        D
	  -                                                                I
	  -                                                                V
	  -                                                                I
	  -                                                                S
	  -                                                                I
	  -                                                                O
	  -                                                                N
	       .
´´´

Even if this should not be expected it could be done (in any ANSI COBOL 85 compiler), newer COBOL standards marked this as obsolete feature where continuation lines should only be used for string literals.

To be clear: it's not "take 100 hours to support this"-post, more a (maybe little funny) anecdote of COBOL.

**Comment by GitMensch** [comment]
Doesn't work for me:

       CONFIGURATION SECTION.

is recognized as before, but

       CONFIGURATION SECTION .

is still not recognized.

- OpenCobolIDE: 4.6.0.dev11
- Python: 3.4.3 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3.dev14
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
You need to update pyqode.cobol^^ (and pyqode.core for #134 )

**Comment by GitMensch** [comment]
Changed my update script, it now reads:

      pip3 install git+http://github.com/pyQode/pyqode.core.git --upgrade
      pip3 install git+http://github.com/pyQode/pyqode.cobol.git --upgrade
      pip3 install git+http://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade

Works now. Thank you.

**Comment by ColinDuquesnoy** [comment]
You might want to add ``pyqode.qt`` to your update script (it usually does not get much updates but it would be safer).

**Comment by GitMensch** [comment]
Thank you, did so.

If you added the version number hack for dev versions in all these for projects it shouldn't be necessary to force the install by --upgrade, should it?

In any case it could be a good idea to provide this upgrade script to Python/Scripts when running setup.py for OCIDE. Should I open a new Enhancement issue for this?

**Comment by ColinDuquesnoy** [comment]
> If you added the version number hack for dev versions in all these for projects it shouldn't be necessary to force the install by --upgrade, should it?

No the upgrade should still be necessary, pip won't upgrade a package that is already installed if you don't tell it to do so, hence the ``--upgrade`` flag.

> In any case it could be a good idea to provide this upgrade script to Python/Scripts when running setup.py for OCIDE. Should I open a new Enhancement issue for this?

No I don't think so, this is needed only because you want to try the try the latest development version, for regular users using the stable release ``pip install OpenCobolIDE --upgrade`` is enough to get the latest version of both the IDE and all its dependencies.

It's not even useful for developers because we typically install all dependencies we might be working on (e.g. all pyqode packages and OpenCobolIDE) as editable packages from git checkout (``pip install -e .`` once and ``git pull`` to update). It really depends on your workflow...
